config/routes.rb
CentroComputo::Application.routes.draw do
    
  resources :computadoras
  resources :usuarios
  resources :consulta_uso
  match 'muestra_usos' => "consulta_uso#muestra_usos", :as => 'muestra_usos'
  match 'show_available' => "usos#show_available", :as => 'show_available'
  match 'select_users/:id' => "usos#select_users", :as => 'select_users'
  match 'save_uso' => 'usos#save_uso', :as => 'save_uso'
  match 'insert_user' => 'usos#insert_users', :as => 'insert_users'
  match 'release_machine' => 'usos#release_machine', :as => 'release_machine'
  
   root :to => 'usos#show_available'


end

app/models/computadora.rb
class Computadora < ActiveRecord::Base
  has_one :ultimo_uso,
:class_name => 'Uso',
:conditions => ["hora_salida is NULL"]

  attr_accessible :descripcion, :estado, :ip
  has_many :usos
end

app/models/uso.rb
class Uso < ActiveRecord::Base
  attr_accessible :hora_llegada, :hora_salida
  belongs_to :usuario
  belongs_to :computadora
  
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :apellido_materno, :apellido_paterno, :estado, :matricula, :nombre
  has_many :usos
  has_many :usos_recientes, :class_name => 'Uso', :conditions => ["hora_llegada.month=?",Date.today.month]
  has_one :ultimo_uso, :class_name => 'Uso', :conditions => ["hora_salida is NULL",NIL]
  has_many :computadoras, :through => :usos
  
  validates :nombre, :presence => true
  
  def full_name
    "#{nombre} #{apellido_paterno} #{apellido_materno}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/computadoras_controller.rb
class ComputadorasController < ApplicationController
  # GET /computadoras
  # GET /computadoras.json
  def index
    @computadoras = Computadora.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @computadoras }
    end
  end

  # GET /computadoras/1
  # GET /computadoras/1.json
  def show
    @computadora = Computadora.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @computadora }
    end
  end

  # GET /computadoras/new
  # GET /computadoras/new.json
  def new
    @computadora = Computadora.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @computadora }
    end
  end

  # GET /computadoras/1/edit
  def edit
    @computadora = Computadora.find(params[:id])
  end

  # POST /computadoras
  # POST /computadoras.json
  def create
    @computadora = Computadora.new(params[:computadora])

    respond_to do |format|
      if @computadora.save
        format.html { redirect_to @computadora, notice: 'Computadora was successfully created.' }
        format.json { render json: @computadora, status: :created, location: @computadora }
      else
        format.html { render action: "new" }
        format.json { render json: @computadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /computadoras/1
  # PUT /computadoras/1.json
  def update
    @computadora = Computadora.find(params[:id])

    respond_to do |format|
      if @computadora.update_attributes(params[:computadora])
        format.html { redirect_to @computadora, notice: 'Computadora was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @computadora.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computadoras/1
  # DELETE /computadoras/1.json
  def destroy
    @computadora = Computadora.find(params[:id])
    @computadora.destroy

    respond_to do |format|
      format.html { redirect_to computadoras_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/consulta_uso_controller.rb
class ConsultaUsoController < ApplicationController
  def index
    
  
  end
  
  
  def muestra_usos
    
    #selected_day=Date.strptime(params[:fecha],'%m/%d/%Y')
#offset=Time.now.utc_offset
#bod= selected_day.beginning_of_day.utc-offset
#eod= selected_day.end_of_day.utc-offset
 
    if(params[:fecha]=="" )
      
      redirect_to show_available_path, notice: 'Fecha invalida.' 
    else
      
      selected_day=Date.strptime(params[:fecha],'%m/%d/%Y')
      @usos=Uso.all(:include => [:computadora, :usuario],:conditions => {"usos.hora_llegada" => selected_day.beginning_of_day..selected_day.end_of_day})
    end
  end
  
  
  
end

app/controllers/usos_controller.rb
class UsosController < ApplicationController
  def show_available
    @computadoras = Computadora.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @computadoras }
    end
    
  end

  def select_users
    @computadora = Computadora.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @computadora }
    end
  end
  
  def save_uso
    @computadora = Computadora.find(params[:computadora])
    @usuario = Usuario.find_by_matricula(params[:matricula])
    if @usuario == nil
      redirect_to show_available_path, notice: 'Usuario invalido.'
    else
            if
      @uso=@usuario.usos.create
      @uso.hora_llegada=Time.now
      @uso.usuario=@usuario
      @uso.computadora=@computadora
      @computadora.estado=false
      @usuario.estado=false
      @computadora.save
      @usuario.save
      @uso.save
      
      redirect_to show_available_path, notice: 'Maquina registrada correctamente.'
    else
          
        redirect_to select_users_path, notice: 'Matricula invalida.'
     
      
    end
  end
  end
  
  def insert_users
    
  end
  
  def release_machine
    @usuario = Usuario.find_by_matricula(params[:matricula]) 
    if @usuario
      @uso= @usuario.ultimo_uso
      if @uso
        @usuario.estado=true
        @uso.computadora.estado=true
        @uso.computadora.save
        @uso.hora_salida=Time.now
        @uso.save
        @usuario.save
        redirect_to show_available_path, notice: 'Salida registrada correctamente.'
      else
        redirect_to show_available_path, notice: 'No tiene computadora en uso actualmente.'
      end
    else
      redirect_to insert_users_path, notice: 'Matricula invalida.'
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usuarios }
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/new
  # GET /usuarios/new.json
  def new
    @usuario = Usuario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  # GET /usuarios/1/edit
  def edit
    @usuario = Usuario.find(params[:id])
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(params[:usuario])

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /usuarios/1
  # PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(params[:usuario])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario = Usuario.find(params[:id])
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/application_helper_1.rb
module ApplicationHelper
end

app/helpers/computadoras_helper.rb
module ComputadorasHelper
end

app/helpers/consulta_uso_helper.rb
module ConsultaUsoHelper
end

app/helpers/consulta_usos_helper.rb
module ConsultaUsosHelper
end

app/helpers/usos_helper.rb
module UsosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/computadoras/_form.html.erb
<%= form_for(@computadora) do |f| %>
  <% if @computadora.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computadora.errors.count, "error") %> prohibited this computadora from being saved:</h2>

      <ul>
      <% @computadora.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computadoras/edit.html.erb
<h1>Editing computadora</h1>

<%= render 'form' %>

<%= link_to 'Show', @computadora %> |
<%= link_to 'Back', computadoras_path %>

app/views/computadoras/index.html.erb
<h1>Listing computadoras</h1>

<table>
  <tr>
    <th>Descripcion</th>
    <th>Ip</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @computadoras.each do |computadora| %>
  <tr>
    <td><%= computadora.descripcion %></td>
    <td><%= computadora.ip %></td>
    <td><%= computadora.estado %></td>
    <td><%= link_to 'Show', computadora %></td>
    <td><%= link_to 'Edit', edit_computadora_path(computadora) %></td>
    <td><%= link_to 'Destroy', computadora, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Computadora', new_computadora_path %>

app/views/computadoras/new.html.erb
<h1>New computadora</h1>

<%= render 'form' %>

<%= link_to 'Back', computadoras_path %>

app/views/computadoras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Descripcion:</b>
  <%= @computadora.descripcion %>
</p>

<p>
  <b>Ip:</b>
  <%= @computadora.ip %>
</p>

<p>
  <b>Estado:</b>
  <%= @computadora.estado %>
</p>


<%= link_to 'Edit', edit_computadora_path(@computadora) %> |
<%= link_to 'Back', computadoras_path %>

app/views/consulta_uso/index.html.erb
<h1>Selleciona el dia que quieras consultar</h1>


<script>
  $(function() {
    $( "#datepicker" ).datepicker();
  });
</script>



<%= form_tag muestra_usos_path do %>
  <p>
    Fecha: <%= text_field_tag :fecha, "",:size => 10, :id=>"datepicker"  %>
    <%= submit_tag "Seleccionar" %>
  </p>

<% end %>

  
  
    

app/views/consulta_uso/muestra_usos.html.erb
<tabla border="1" >
  <tr>
    <td><h3>Matricula</h3></td>
    <td><h3>Maquina</h3></td>
    <td><h3>Nombre</h3></td>
    <td><h3>Ap paterno</h3></td>
    <td><h3>Ap materno</h3></td>
    <td><h3>Llegada</h3></td>
    <td><h3>Salida</h3></td>
  </tr>

 <% @usos.each do |uso| %>
    <tr>
      <td><%= uso.usuario.matricula %>  </td>
      <td><%= uso.computadora.descripcion %>--- </td>
      <td><%= uso.usuario.nombre %> </td>

      <td><%= uso.usuario.apellido_paterno %> </td>
      <td><%= uso.usuario.apellido_materno %> </td>

      <td><%= uso.hora_llegada.strftime("%Y-%m-%d %H:%M") %> ---</td>
      <%
      if(uso.hora_salida == nil)
      %>
        <td>No cerro sesion</td>
      <%else%>
        <td><%= uso.hora_salida.strftime("%Y-%m-%d %H:%M") %> --- </td>
      <%end%>
    </tr>

  <% end %>

</tabla>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Universidad Politecnica de Tlaxcala</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
 
    <meta charset="utf-8" />
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.8.2.js"></script>
    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css" />
  </head>
  <body>

  <center>
    <h1 style="color: green">
      Universidad Politecnica de Tlaxcala
    </h1>
  </center>
  <center>
    <h2 style="color:green">Region Poniente</h2>
    <p>
      <a href="show_available">Inicio</a>
    </p>
  </center>  

  <table align="center" >
    <tr>
      <td>
        <% if flash[:alert] %>
          <p class="flash-error"><%= flash[:alert] %></p>
        <% end %>
        <% if flash[:notice] %>
          <p class="flash-notice"><%= flash[:notice] %></p>
        <% end %>
        <%= yield %>
      </td>
    </tr>
  </table>

</body>
</html>

app/views/usos/insert_users.html.erb
<h1>Escribe tu matricula</h1>


<%= form_tag release_machine_path do %>
  <p>Matricula: <%= text_field_tag :matricula, "",:size => 30  %> </p>
  <p> <%= submit_tag "Seleccionar" %>  </p>
<% end %>

app/views/usos/select_users.html.erb
<h1>Escribe tu matricula</h1>
<%= form_tag save_uso_path do %>
  <p>Matricula: <%= text_field_tag :matricula, "",:size => 30  %> </p>
  <%= hidden_field_tag :computadora, @computadora.id %>
  <p> <%= submit_tag "Seleccionar" %>  </p>
<% end %>

app/views/usos/show_available.html.erb
<h1>Selecciona una computadora<h1>

    <table >
      <% @computadoras.each do |computadora| %>
        <tr class="computadora<%= computadora.estado %> ">
          <td><%= computadora.descripcion %></td>
          
          <td style="">
            
            <%= computadora.ultimo_uso ? computadora.ultimo_uso.usuario.full_name : ""   %>
          </td>
          <% if  computadora.estado %>
            <td><%= link_to 'Seleccionar', select_users_path(computadora) %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    
    <%= link_to 'Liberar', insert_users_path %>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :matricula %><br />
    <%= f.text_field :matricula %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido_paterno %><br />
    <%= f.text_field :apellido_paterno %>
  </div>
  <div class="field">
    <%= f.label :apellido_materno %><br />
    <%= f.text_field :apellido_materno %>
  </div>
  <div class="field">
    <%= f.label :estado %><br />
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<h1>Listing usuarios</h1>

<table>
  <tr>
    <th>Matricula</th>
    <th>Nombre</th>
    <th>Apellido paterno</th>
    <th>Apellido materno</th>
    <th>Estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usuarios.each do |usuario| %>
  <tr>
    <td><%= usuario.matricula %></td>
    <td><%= usuario.nombre %></td>
    <td><%= usuario.apellido_paterno %></td>
    <td><%= usuario.apellido_materno %></td>
    <td><%= usuario.estado %></td>
    <td><%= link_to 'Show', usuario %></td>
    <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
    <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Matricula:</b>
  <%= @usuario.matricula %>
</p>

<p>
  <b>Nombre:</b>
  <%= @usuario.nombre %>
</p>

<p>
  <b>Apellido paterno:</b>
  <%= @usuario.apellido_paterno %>
</p>

<p>
  <b>Apellido materno:</b>
  <%= @usuario.apellido_materno %>
</p>

<p>
  <b>Estado:</b>
  <%= @usuario.estado %>
</p>


<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>